    -- IF NOT EXIST ES PORQUE GARANTIZA QUE SE CREE LA TABLA SI LA ENTIDAD LLEGA A FALLAR
    --Y ASI NO SE GENERA ERROR AL INTENTAR INSERTAR DATOS A UNA TABLA QUE NO EXISTE
    CREATE TABLE IF NOT EXISTS 
fases
(
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
    );
-- INSERT INGNORE INTO INSERTA LOS DATOS PERO SI ESTOS YA EXISTEN SOLO LOS IGNORA
INSERT IGNORE INTO fases (id, nombre) VALUES
(1, 'PENDIENTE'),
(2, 'EN_PREPARACION'),
(3, 'CANCELADO'),
(4, 'LISTO'),
(5, 'ENTREGADO');

CREATE TABLE IF NOT EXISTS 
rol
(
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
    );
    -- INSERT INGNORE INTO INSERTA LOS DATOS PERO SI ESTOS YA EXISTEN SOLO LOS IGNORA
INSERT IGNORE INTO rol (id, nombre) VALUES
(1,'ADMINISTRADOR'),
(2,'PROPIETARIO'),
(3,'CLIENTE'),
(4,'EMPLEADO');
